-- =============================================================================
-- KALDORA — Léxicos por categoría (validación semántica del Basta)
-- =============================================================================
-- Cada categoría con `clave_lexico` valida que la palabra exista EN esa
-- categoría. Categorías abiertas (película, marca, objeto, mar) validan solo
-- contra el diccionario + el criterio del anfitrión.

create table if not exists public.lexico_categorias (
  id          uuid primary key default gen_random_uuid(),
  id_categoria uuid not null references public.categorias_basta(id) on delete cascade,
  palabra     text not null,
  creado_en   timestamptz not null default now()
);

create unique index if not exists uq_lexico_categoria_palabra
  on public.lexico_categorias (id_categoria, palabra);

alter table public.lexico_categorias enable row level security;
revoke all privileges on public.lexico_categorias from anon, authenticated;

insert into public.lexico_categorias (id_categoria, palabra)
select c.id, v.palabra
  from (values
    -- ANIMAL ----------------------------------------------------------------
    ('animal','perro'),('animal','gato'),('animal','caballo'),('animal','vaca'),
    ('animal','cerdo'),('animal','oveja'),('animal','cabra'),('animal','gallina'),
    ('animal','gallo'),('animal','pollo'),('animal','pavo'),('animal','pato'),
    ('animal','ganso'),('animal','conejo'),('animal','raton'),('animal','rata'),
    ('animal','hamster'),('animal','huron'),('animal','zorro'),('animal','lobo'),
    ('animal','oso'),('animal','leon'),('animal','tigre'),('animal','jaguar'),
    ('animal','puma'),('animal','leopardo'),('animal','guepardo'),('animal','elefante'),
    ('animal','rinoceronte'),('animal','hipopotamo'),('animal','jirafa'),('animal','cebra'),
    ('animal','camello'),('animal','dromedario'),('animal','llama'),('animal','alpaca'),
    ('animal','vicuna'),('animal','guanaco'),('animal','canguro'),('animal','koala'),
    ('animal','panda'),('animal','mapache'),('animal','mofeta'),('animal','perezoso'),
    ('animal','mono'),('animal','gorila'),('animal','chimpance'),('animal','orangutan'),
    ('animal','murcielago'),('animal','delfin'),('animal','orca'),('animal','ballena'),
    ('animal','cachalote'),('animal','tiburon'),('animal','pulpo'),('animal','calamar'),
    ('animal','salmon'),('animal','trucha'),('animal','atun'),('animal','merluza'),
    ('animal','sardina'),('animal','anchoa'),('animal','bacalao'),('animal','lenguado'),
    ('animal','carpa'),('animal','tilapia'),('animal','bagre'),('animal','tararira'),
    ('animal','boga'),('animal','pejerrey'),('animal','mojarra'),('animal','aguila'),
    ('animal','halcon'),('animal','buho'),('animal','lechuza'),('animal','loro'),
    ('animal','cotorra'),('animal','guacamayo'),('animal','tucan'),('animal','colibri'),
    ('animal','flamenco'),('animal','cisne'),('animal','pinguino'),('animal','avestruz'),
    ('animal','nandu'),('animal','emu'),('animal','casuario'),('animal','pelicano'),
    ('animal','gaviota'),('animal','paloma'),('animal','gorrion'),('animal','canario'),
    ('animal','jilguero'),('animal','ruisenor'),('animal','cuervo'),('animal','urraca'),
    ('animal','armadillo'),('animal','carpincho'),('animal','capibara'),('animal','coipo'),
    ('animal','nutria'),('animal','yaguarete'),('animal','mara'),('animal','vizcacha'),
    ('animal','chinchilla'),('animal','cormoran'),('animal','garza'),('animal','ciguena'),
    ('animal','condor'),('animal','vibora'),('animal','culebra'),('animal','serpiente'),
    ('animal','anaconda'),('animal','iguana'),('animal','lagarto'),('animal','lagartija'),
    ('animal','camaleon'),('animal','cocodrilo'),('animal','caiman'),('animal','tortuga'),
    ('animal','rana'),('animal','sapo'),('animal','salamandra'),('animal','tarantula'),
    ('animal','arana'),('animal','alacran'),('animal','escorpion'),('animal','hormiga'),
    ('animal','abeja'),('animal','avispa'),('animal','mosca'),('animal','mosquito'),
    ('animal','mariposa'),('animal','polilla'),('animal','escarabajo'),('animal','luciernaga'),
    ('animal','grillo'),('animal','saltamontes'),('animal','langosta'),('animal','gusano'),
    ('animal','lombriz'),('animal','caracol'),('animal','babosa'),('animal','medusa'),
    ('animal','cangrejo'),('animal','camaron'),('animal','langostino'),('animal','almeja'),
    ('animal','mejillon'),('animal','ostra'),('animal','erizo'),('animal','pirana'),
    ('animal','ornitorrinco'),('animal','equidna'),('animal','alce'),('animal','reno'),
    ('animal','bisonte'),('animal','bufalo'),('animal','lince'),('animal','pantera'),
    ('animal','hiena'),('animal','chacal'),('animal','coyote'),('animal','castor'),
    ('animal','tejon'),('animal','comadreja'),('animal','marmota'),('animal','ardilla'),
    ('animal','topo'),('animal','erizo'),('animal','suricata'),('animal','lemur'),
    -- PAÍS O CIUDAD ------------------------------------------------------------
    ('pais','argentina'),('pais','uruguay'),('pais','paraguay'),('pais','chile'),
    ('pais','bolivia'),('pais','peru'),('pais','ecuador'),('pais','colombia'),
    ('pais','venezuela'),('pais','brasil'),('pais','mexico'),('pais','guatemala'),
    ('pais','belice'),('pais','honduras'),('pais','elsalvador'),('pais','nicaragua'),
    ('pais','costarica'),('pais','panama'),('pais','cuba'),('pais','jamaica'),
    ('pais','haiti'),('pais','espana'),('pais','portugal'),('pais','francia'),
    ('pais','italia'),('pais','alemania'),('pais','inglaterra'),('pais','irlanda'),
    ('pais','escocia'),('pais','gales'),('pais','suiza'),('pais','austria'),
    ('pais','belgica'),('pais','holanda'),('pais','paisesbajos'),('pais','dinamarca'),
    ('pais','noruega'),('pais','suecia'),('pais','finlandia'),('pais','islandia'),
    ('pais','polonia'),('pais','hungria'),('pais','rumania'),('pais','bulgaria'),
    ('pais','grecia'),('pais','turquia'),('pais','rusia'),('pais','ucrania'),
    ('pais','moldavia'),('pais','estonia'),('pais','letonia'),('pais','lituania'),
    ('pais','albania'),('pais','croacia'),('pais','eslovenia'),('pais','serbia'),
    ('pais','macedonia'),('pais','malta'),('pais','chipre'),('pais','monaco'),
    ('pais','andorra'),('pais','marruecos'),('pais','argelia'),('pais','tunez'),
    ('pais','libia'),('pais','egipto'),('pais','etiopia'),('pais','kenia'),
    ('pais','tanzania'),('pais','uganda'),('pais','nigeria'),('pais','ghana'),
    ('pais','senegal'),('pais','mali'),('pais','chad'),('pais','camerun'),
    ('pais','congo'),('pais','angola'),('pais','zambia'),('pais','zimbabue'),
    ('pais','mozambique'),('pais','madagascar'),('pais','namibia'),('pais','sudafrica'),
    ('pais','somalia'),('pais','saudiarabia'),('pais','yemen'),('pais','oman'),
    ('pais','qatar'),('pais','kuwait'),('pais','irak'),('pais','iran'),
    ('pais','siria'),('pais','libano'),('pais','israel'),('pais','jordania'),
    ('pais','india'),('pais','pakistan'),('pais','bangladesh'),('pais','nepal'),
    ('pais','butan'),('pais','china'),('pais','japon'),('pais','corea'),
    ('pais','mongolia'),('pais','taiwan'),('pais','filipinas'),('pais','vietnam'),
    ('pais','laos'),('pais','camboya'),('pais','tailandia'),('pais','malasia'),
    ('pais','singapur'),('pais','indonesia'),('pais','australia'),('pais','nuevazelanda'),
    ('pais','buenosaires'),('pais','cordoba'),('pais','rosario'),('pais','mendoza'),
    ('pais','salta'),('pais','tucuman'),('pais','neuquen'),('pais','ushuaia'),
    ('pais','bariloche'),('pais','laplata'),('pais','marplate'),('pais','montevideo'),
    ('pais','asuncion'),('pais','bogota'),('pais','medellin'),('pais','cali'),
    ('pais','caracas'),('pais','lima'),('pais','quito'),('pais','guayaquil'),
    ('pais','santiago'),('pais','brasilia'),('pais','riodejaneiro'),('pais','saopaulo'),
    ('pais','madrid'),('pais','barcelona'),('pais','valencia'),('pais','sevilla'),
    ('pais','paris'),('pais','londres'),('pais','roma'),('pais','milan'),
    ('pais','berlin'),('pais','munich'),('pais','amsterdam'),('pais','bruselas'),
    ('pais','viena'),('pais','praga'),('pais','atenas'),('pais','lisboa'),
    ('pais','moscu'),('pais','kiev'),('pais','estocolmo'),('pais','oslo'),
    ('pais','helsinki'),('pais','dublin'),('pais','varsovia'),('pais','budapest'),
    ('pais','bucarest'),('pais','estambul'),('pais','elcairo'),('pais','tokio'),
    ('pais','pekin'),('pais','seul'),('pais','bangkok'),('pais','sidney'),
    ('pais','toronto'),('pais','montreal'),('pais','quebec'),('pais','newyork'),
    ('pais','losangeles'),('pais','miami'),('pais','chicago'),('pais','boston'),
    ('pais','houston'),('pais','dubai'),('pais','jerusalen'),('pais','telaviv'),
    ('pais','lahabana'),('pais','santodomingo'),
    -- COLOR -----------------------------------------------------------------
    ('color','rojo'),('color','azul'),('color','verde'),('color','amarillo'),
    ('color','negro'),('color','blanco'),('color','gris'),('color','naranja'),
    ('color','violeta'),('color','lila'),('color','rosa'),('color','celeste'),
    ('color','turquesa'),('color','marron'),('color','castano'),('color','magenta'),
    ('color','fucsia'),('color','beige'),('color','crema'),('color','dorado'),
    ('color','plateado'),('color','cobre'),('color','bronce'),('color','oliva'),
    ('color','ocre'),('color','burdeos'),('color','granate'),('color','guinda'),
    ('color','salmon'),('color','indigo'),('color','lavanda'),('color','mostaza'),
    ('color','terracota'),('color','malva'),('color','carmesi'),('color','escarlata'),
    ('color','esmeralda'),('color','plomo'),('color','perla'),('color','marfil'),
    ('color','ebano'),('color','grafito'),('color','arena'),('color','caramelo'),
    ('color','chocolate'),('color','cafe'),('color','cobrizo'),('color','ambar'),
    ('color','bermellon'),('color','ocre'),('color','ceniza'),('color','humo'),
    -- FRUTA O VERDURA ---------------------------------------------------------
    ('fruta','manzana'),('fruta','pera'),('fruta','durazno'),('fruta','nectarina'),
    ('fruta','banana'),('fruta','platano'),('fruta','naranja'),('fruta','mandarina'),
    ('fruta','clementina'),('fruta','limon'),('fruta','lima'),('fruta','pomelo'),
    ('fruta','anana'),('fruta','pina'),('fruta','frutilla'),('fruta','fresa'),
    ('fruta','arandano'),('fruta','frambuesa'),('fruta','mora'),('fruta','grosella'),
    ('fruta','uva'),('fruta','pasa'),('fruta','higo'),('fruta','damasco'),
    ('fruta','cereza'),('fruta','guinda'),('fruta','melon'),('fruta','sandia'),
    ('fruta','kiwi'),('fruta','mango'),('fruta','papaya'),('fruta','palta'),
    ('fruta','aguacate'),('fruta','coco'),('fruta','guayaba'),('fruta','maracuya'),
    ('fruta','granada'),('fruta','tamarindo'),('fruta','chirimoya'),('fruta','lichi'),
    ('fruta','kaki'),('fruta','datil'),('fruta','castana'),('fruta','nuez'),
    ('fruta','almendra'),('fruta','avellana'),('fruta','mani'),('fruta','pistacho'),
    ('fruta','lechuga'),('fruta','acelga'),('fruta','espinaca'),('fruta','rucula'),
    ('fruta','repollo'),('fruta','coliflor'),('fruta','brocoli'),('fruta','zanahoria'),
    ('fruta','remolacha'),('fruta','rabanito'),('fruta','pepino'),('fruta','zapallito'),
    ('fruta','zapallo'),('fruta','calabaza'),('fruta','tomate'),('fruta','pimiento'),
    ('fruta','morron'),('fruta','cebolla'),('fruta','ajo'),('fruta','puerro'),
    ('fruta','apio'),('fruta','papa'),('fruta','batata'),('fruta','camote'),
    ('fruta','mandioca'),('fruta','choclo'),('fruta','arvejas'),('fruta','habas'),
    ('fruta','chauchas'),('fruta','esparragos'),('fruta','alcachofa'),('fruta','champignon'),
    ('fruta','berenjena'),('fruta','higos'),('fruta','melocoton'),
    -- COMIDA O PLATO -----------------------------------------------------------
    ('comida','asado'),('comida','milanesa'),('comida','empanada'),('comida','locro'),
    ('comida','guiso'),('comida','estofado'),('comida','pizza'),('comida','fideos'),
    ('comida','canelones'),('comida','noquis'),('comida','ravioles'),('comida','tallarines'),
    ('comida','tortilla'),('comida','pascualina'),('comida','tarta'),('comida','matambre'),
    ('comida','choripan'),('comida','humita'),('comida','tamal'),('comida','polenta'),
    ('comida','risotto'),('comida','paella'),('comida','sopa'),('comida','ensalada'),
    ('comida','flan'),('comida','budin'),('comida','helado'),('comida','merengue'),
    ('comida','mousse'),('comida','panqueque'),('comida','churros'),('comida','alfajor'),
    ('comida','medialuna'),('comida','pancho'),('comida','hamburguesa'),('comida','sandwich'),
    ('comida','tostado'),('comida','mondongo'),('comida','achuras'),('comida','chinchulin'),
    ('comida','morcilla'),('comida','salchicha'),('comida','ceviche'),('comida','lomito'),
    ('comida','bife'),('comida','vacio'),('comida','entrana'),('comida','costilla'),
    ('comida','arroz'),('comida','lentejas'),('comida','garbanzos'),('comida','sushi'),
    ('comida','tiramisu'),('comida','brownie'),('comida','cheesecake'),('comida','golosina'),
    ('comida','caramelo'),('comida','chicle'),('comida','chocolate'),('comida','turron'),
    ('comida','galletita'),('comida','galleta'),('comida','bizcocho'),('comida','torta'),
    ('comida','tartaleta'),('comida','cannoli'),('comida','sorrentinos'),
    -- DEPORTE -----------------------------------------------------------------
    ('deporte','futbol'),('deporte','basquet'),('deporte','baloncesto'),('deporte','voley'),
    ('deporte','tenis'),('deporte','padel'),('deporte','squash'),('deporte','badminton'),
    ('deporte','gimnasia'),('deporte','atletismo'),('deporte','natacion'),('deporte','waterpolo'),
    ('deporte','hockey'),('deporte','rugby'),('deporte','boxeo'),('deporte','lucha'),
    ('deporte','judo'),('deporte','karate'),('deporte','taekwondo'),('deporte','aikido'),
    ('deporte','esgrima'),('deporte','ciclismo'),('deporte','escalada'),('deporte','alpinismo'),
    ('deporte','trekking'),('deporte','maraton'),('deporte','triatlon'),('deporte','equitacion'),
    ('deporte','polo'),('deporte','golf'),('deporte','cricket'),('deporte','beisbol'),
    ('deporte','softbol'),('deporte','bolera'),('deporte','billar'),('deporte','snooker'),
    ('deporte','dardos'),('deporte','ajedrez'),('deporte','pesas'),('deporte','crossfit'),
    ('deporte','pilates'),('deporte','yoga'),('deporte','buceo'),('deporte','surf'),
    ('deporte','windsurf'),('deporte','kitesurf'),('deporte','kayak'),('deporte','canotaje'),
    ('deporte','remo'),('deporte','vela'),('deporte','regata'),('deporte','pesca'),
    ('deporte','tiro'),('deporte','patinaje'),('deporte','esqui'),('deporte','snowboard'),
    ('deporte','skate'),('deporte','paracaidismo'),('deporte','aladelta'),('deporte','rafting'),
    ('deporte','spinning'),('deporte','zumba'),('deporte','capoeira'),('deporte','sumo'),
    ('deporte','bmx'),('deporte','automovilismo'),('deporte','motociclismo'),('deporte','rally'),
    ('deporte','karting'),('deporte','motocross'),('deporte','fronton'),('deporte','pelota'),
    ('deporte','handball'),('deporte','petanca'),('deporte','tejo'),('deporte','rayuela'),
    -- PROFESIÓN U OFICIO -------------------------------------------------------
    ('profesion','medico'),('profesion','doctor'),('profesion','enfermero'),('profesion','enfermera'),
    ('profesion','dentista'),('profesion','odontologo'),('profesion','psicologo'),('profesion','psiquiatra'),
    ('profesion','veterinario'),('profesion','abogado'),('profesion','juez'),('profesion','fiscal'),
    ('profesion','escribano'),('profesion','procurador'),('profesion','ingeniero'),('profesion','arquitecto'),
    ('profesion','agronomo'),('profesion','contador'),('profesion','economista'),('profesion','profesor'),
    ('profesion','maestro'),('profesion','docente'),('profesion','rector'),('profesion','bibliotecario'),
    ('profesion','cientifico'),('profesion','investigador'),('profesion','fisico'),('profesion','quimico'),
    ('profesion','biologo'),('profesion','matematico'),('profesion','astronauta'),('profesion','piloto'),
    ('profesion','azafata'),('profesion','mecanico'),('profesion','electricista'),('profesion','plomero'),
    ('profesion','gasista'),('profesion','carpintero'),('profesion','albanil'),('profesion','pintor'),
    ('profesion','herrero'),('profesion','soldador'),('profesion','cerrajero'),('profesion','vidriero'),
    ('profesion','alfarero'),('profesion','orfebre'),('profesion','joyero'),('profesion','relojero'),
    ('profesion','sastre'),('profesion','modista'),('profesion','costurera'),('profesion','peluquero'),
    ('profesion','barbero'),('profesion','manicura'),('profesion','maquilladora'),('profesion','esteticista'),
    ('profesion','cocinero'),('profesion','chef'),('profesion','pastelero'),('profesion','panadero'),
    ('profesion','mozo'),('profesion','camarero'),('profesion','bartender'),('profesion','barman'),
    ('profesion','sommelier'),('profesion','cajero'),('profesion','vendedor'),('profesion','dependiente'),
    ('profesion','comerciante'),('profesion','empresario'),('profesion','emprendedor'),('profesion','periodista'),
    ('profesion','redactor'),('profesion','editor'),('profesion','fotografo'),('profesion','director'),
    ('profesion','productor'),('profesion','actor'),('profesion','actriz'),('profesion','cantante'),
    ('profesion','musico'),('profesion','guitarrista'),('profesion','pianista'),('profesion','violinista'),
    ('profesion','bailarina'),('profesion','bailarin'),('profesion','coreografo'),('profesion','escultor'),
    ('profesion','escritor'),('profesion','poeta'),('profesion','dibujante'),('profesion','ilustrador'),
    ('profesion','traductor'),('profesion','interprete'),('profesion','policia'),('profesion','gendarme'),
    ('profesion','bombero'),('profesion','soldado'),('profesion','militar'),('profesion','general'),
    ('profesion','sargento'),('profesion','capitan'),('profesion','almirante'),('profesion','guardavidas'),
    ('profesion','socorrista'),('profesion','chofer'),('profesion','taxista'),('profesion','remisero'),
    ('profesion','camionero'),('profesion','repartidor'),('profesion','mensajero'),('profesion','cartero'),
    ('profesion','jardinero'),('profesion','granjero'),('profesion','campesino'),('profesion','ganadero'),
    ('profesion','lechero'),('profesion','pescador'),('profesion','minero'),('profesion','petrolero'),
    ('profesion','zapatero'),('profesion','limpiador'),('profesion','mucama'),('profesion','ninera'),
    ('profesion','estudiante'),('profesion','becario'),('profesion','pasante'),('profesion','programador'),
    ('profesion','desarrollador'),('profesion','informatico'),('profesion','disenador'),('profesion','politico'),
    ('profesion','diputado'),('profesion','senador'),('profesion','presidente'),('profesion','intendente'),
    ('profesion','gobernador'),('profesion','ministro'),('profesion','embajador'),('profesion','consul'),
    ('profesion','sociologo'),('profesion','antropologo'),('profesion','arqueologo'),('profesion','historiador'),
    ('profesion','filosofo'),('profesion','matrona'),('profesion','osteopata'),('profesion','kinesiologo'),
    ('profesion','fonoaudiologo'),('profesion','terapista'),('profesion','optometrista'),('profesion','farmaceutico'),
    -- NOMBRE DE PERSONA ---------------------------------------------------------
    ('persona','juan'),('persona','jose'),('persona','pedro'),('persona','pablo'),
    ('persona','lucas'),('persona','miguel'),('persona','angel'),('persona','francisco'),
    ('persona','javier'),('persona','antonio'),('persona','manuel'),('persona','carlos'),
    ('persona','daniel'),('persona','jorge'),('persona','rafael'),('persona','fernando'),
    ('persona','sergio'),('persona','santiago'),('persona','mateo'),('persona','emiliano'),
    ('persona','martin'),('persona','nicolas'),('persona','agustin'),('persona','tomas'),
    ('persona','fausto'),('persona','felipe'),('persona','julio'),('persona','cesar'),
    ('persona','marcelo'),('persona','ariel'),('persona','adrian'),('persona','leonel'),
    ('persona','cristian'),('persona','hector'),('persona','diego'),('persona','claudio'),
    ('persona','gustavo'),('persona','rodrigo'),('persona','alejandro'),('persona','federico'),
    ('persona','ezequiel'),('persona','damian'),('persona','ignacio'),('persona','marcos'),
    ('persona','luis'),('persona','alberto'),('persona','ramon'),('persona','mario'),
    ('persona','eduardo'),('persona','andres'),('persona','oscar'),('persona','vicente'),
    ('persona','ruben'),('persona','norberto'),('persona','dario'),('persona','fabian'),
    ('persona','esteban'),('persona','leandro'),('persona','luciano'),('persona','gonzalo'),
    ('persona','matias'),('persona','facundo'),('persona','maria'),('persona','lucia'),
    ('persona','sofia'),('persona','valentina'),('persona','martina'),('persona','camila'),
    ('persona','isabela'),('persona','josefina'),('persona','florencia'),('persona','julieta'),
    ('persona','agustina'),('persona','magdalena'),('persona','catalina'),('persona','victoria'),
    ('persona','gabriela'),('persona','patricia'),('persona','claudia'),('persona','monica'),
    ('persona','silvina'),('persona','cecilia'),('persona','liliana'),('persona','daniela'),
    ('persona','paula'),('persona','laura'),('persona','elena'),('persona','carla'),
    ('persona','sara'),('persona','ana'),('persona','ines'),('persona','teresa'),
    ('persona','clara'),('persona','rosa'),('persona','susana'),('persona','beatriz'),
    ('persona','marcela'),('persona','viviana'),('persona','norma'),('persona','mirta'),
    ('persona','estela'),('persona','miriam'),('persona','leonor'),('persona','cristina'),
    ('persona','rita'),('persona','elisa'),('persona','angela'),('persona','gloria'),
    ('persona','fernanda'),('persona','veronica'),('persona','andrea'),('persona','mariana'),
    ('persona','carolina'),('persona','noelia'),('persona','natalia'),('persona','yamila'),
    ('persona','yesica'),('persona','daiana'),('persona','morena'),('persona','malena'),
    ('persona','milagros'),('persona','guadalupe'),('persona','ximena'),('persona','jimena'),
    ('persona','belen'),('persona','raquel'),('persona','noemi'),('persona','brenda'),
    ('persona','tamara'),('persona','ariana'),('persona','luciana'),('persona','constanza'),
    ('persona','candela'),('persona','antonella'),('persona','mia'),('persona','alma'),
    ('persona','olivia'),('persona','emilia'),('persona','estanislao'),('persona','bonifacio')
) as v(clave, palabra)
  join public.categorias_basta c on c.clave_lexico = v.clave
on conflict do nothing;
